###

POST http://{{host}}/people
Content-Type: application/json

{
  "name": "John Smith {{$randomInt}}",
  "email": "jsmith{{$randomInt}}@example.com",
  "city": "London {{$randomInt}}",
  "street": "Smith Str {{$randomInt}}",
  "number": "{{$randomInt}}-bis"
}

> {%
    client.global.set("personId", response.body.id);
%}
###

GET http://{{host}}/people/{{personId}}
Accept: application/json

###

GET http://{{host}}/people
Accept: application/json

> {%
    client.global.set("personId", response.body[0].id);
%}
###

PATCH http://{{host}}/people/{{personId}}
Content-Type: application/json

{
  "number": "{{$randomInt}}-bis"
}

###

DELETE http://{{host}}/people/{{personId}}

###

POST http://{{host}}/cars
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "plateNum": "QW-{{$randomInt}}-ER",
  "personId": "{{personId}}"
}

> {%
    client.global.set("carId", response.body.id);
%}
###

GET http://{{host}}/cars/{{carId}}
Accept: application/json

###

GET http://{{host}}/cars
Accept: application/json

> {%
    client.global.set("carId", response.body[0].id);
%}

###

PATCH http://{{host}}/cars/{{carId}}
Content-Type: application/json

{
  "plateNum": "AS-{{$randomInt}}-DF"
}

###

DELETE http://{{host}}/cars/{{carId}}

###

GET http://{{host}}/people/{{personId}}/cars
Accept: application/json

###
